### ISSUE TITLE
微信回调关注响应模板及定时提醒功能模板

### ISSUE THREAD

**Issue by ZhangBohan** [AwesomeGuppies/Hangout#16]
预约成功模板：

```python
data = {
    'first': {
        "value": "恭喜你预约成功!",
        "color": "#173177"
    },
    'keyword1': {
        "value": "标题",
        "color": "#173177"
    },
    'keyword2': {
        "value": "已预约",
        "color": "#173177"
    },
    'keyword3': {
        "value": '%Y年%m月%d日 %H时%M分',
        "color": "#173177"
    },
    'remark': {
        "value": 'laasljflsadkfjbalablab',
        "color": "#173177"
    },
}
wb.send_template_message('oC00cuNKgcd3uuYLFnu7DZik9cpc', settings.WECHAT_NOTIFY_TEMPLATE_ID, data=data, url="https://www.speedx.com")
```

**Comment by ZhangBohan** [comment]
```
web_1  | wechat_base.message: <wechat_sdk.messages.EventMessage object at 0x7fc88830fcc0> scan
web_1  | 关注事件 1 oC00cuA2zCFuFiccmzxtp-bx4aZs
web_1  | auth 张伯函 None
web_1  | ERROR:root:Cannot assign None: "ScheduleUser.user" does not allow null values.
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 465, in get_or_create
web_1  |     return self.get(**lookup), False
web_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 387, in get
web_1  |     self.model._meta.object_name
web_1  | hangout.models.DoesNotExist: ScheduleUser matching query does not exist.
web_1  |
web_1  | During handling of the above exception, another exception occurred:
web_1  |
web_1  | Traceback (most recent call last):
web_1  |   File "/code/GuppiesWechat/wechat/views.py", line 63, in callback
web_1  |     schedule_share = _accept_schedule(ss_id=int(key), user=wechat_auth.user)
web_1  |   File "/code/GuppiesWechat/wechat/views.py", line 101, in _accept_schedule
web_1  |     su, created = ScheduleUser.objects.get_or_create(schedule=schedule_share.schedule, user=user)
web_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 122, in manager_method
web_1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 467, in get_or_create
web_1  |     return self._create_object_from_params(lookup, params)
web_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 499, in _create_object_from_params
web_1  |     obj = self.create(**params)
web_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 399, in create
web_1  |     obj = self.model(**kwargs)
web_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 431, in __init__
web_1  |     setattr(self, field.name, rel_obj)
web_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 199, in __set__
web_1  |     (instance._meta.object_name, self.field.name)
web_1  | ValueError: Cannot assign None: "ScheduleUser.user" does not allow null values.
web_1  | [19/Nov/2016 00:13:55] "POST /wechat/callback?signature=f0fc62675a87cb8789a85174fc90cdf566cef2dd&timestamp=1479485640&nonce=1409392818&openid=oC00cuA2zCFuFiccmzxtp-bx4aZs HTTP/1.0" 200 297
```
